export const frontendHtml = (user: { email?: string } | null) => `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Infinity Agents</title><style>
:root{color-scheme:dark;--bg:#0b0d10;--panel:#11141a;--line:#2a303a;--text:#f2f4f7;--muted:#a4acb9;--signal:#90e56a;--signal-ink:#10230a}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 18% 0,#1b2730 0,transparent 33rem),var(--bg);color:var(--text);font:16px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,"PingFang SC",sans-serif}main{width:min(960px,calc(100% - 32px));margin:auto;padding:32px 0 56px}header{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:38px}h1{font-size:24px;letter-spacing:-.04em;margin:0}.account{display:flex;align-items:center;gap:12px;color:var(--muted);font-size:14px}.button{display:inline-flex;align-items:center;justify-content:center;min-height:38px;padding:9px 14px;border:0;border-radius:9px;background:var(--signal);color:var(--signal-ink);font:700 14px inherit;text-decoration:none;cursor:pointer}.button:hover{filter:brightness(1.07)}.button.secondary{background:transparent;color:var(--text);border:1px solid var(--line)}.panel{border:1px solid var(--line);border-radius:16px;background:color-mix(in srgb,var(--panel) 96%,transparent);overflow:hidden}.intro{padding:28px 28px 8px}.intro h2{font-size:30px;letter-spacing:-.045em;margin:0 0 8px}.muted{color:var(--muted);margin:0}.chat{padding:20px 28px 28px}.composer{position:relative}.composer textarea{display:block;width:100%;min-height:150px;resize:vertical;border:1px solid var(--line);border-radius:12px;background:#090b0e;color:var(--text);padding:16px;font:inherit}.composer textarea:focus{outline:2px solid color-mix(in srgb,var(--signal) 65%,transparent);outline-offset:2px}.actions{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:12px}.hint{font-size:13px;color:var(--muted)}#status{min-height:24px;margin-top:16px;color:var(--muted)}#status a{color:var(--signal);font-weight:700}.output{display:none;min-height:120px;white-space:pre-wrap;overflow:auto;border-top:1px solid var(--line);margin:16px -28px -28px;padding:22px 28px;background:#090b0e;font:15px/1.7 ui-monospace,SFMono-Regular,Menlo,monospace}.output:not(:empty){display:block}@media(max-width:600px){main{width:min(100% - 24px,960px);padding-top:20px}header{margin-bottom:24px}.account span{display:none}.intro,.chat{padding-left:18px;padding-right:18px}.intro h2{font-size:26px}.output{margin-left:-18px;margin-right:-18px;padding-left:18px;padding-right:18px}}</style></head><body><main>
<header><h1>Infinity Agents</h1><div class="account">${user ? `<span>${escapeHtml(user.email ?? "已登录")}</span><a class="button secondary" href="/logout">退出</a>` : `<a class="button" href="/login">登录</a>`}</div></header>
<section class="panel"><div class="intro"><h2>和 Infinity 对话</h2><p class="muted">提出问题、梳理想法，或让它协助你完成下一步。</p></div><div class="chat"><div class="composer"><textarea id="prompt" placeholder="输入你的问题…" aria-label="消息"></textarea></div><div class="actions"><span class="hint">${user ? "已连接到你的 ZhangYvJing 账户" : "发送消息时会要求你登录"}</span><button class="button" id="send" type="button">发送</button></div><div id="status" role="status" aria-live="polite"></div><pre id="output" class="output"></pre></div></section>
<script>
const p=document.querySelector('#prompt'),s=document.querySelector('#send'),o=document.querySelector('#output'),t=document.querySelector('#status');
function loginPrompt(){t.innerHTML='请先 <a href="/login">登录</a>，然后继续对话。'}
s.onclick=async()=>{const message=p.value.trim();if(!message)return;s.disabled=true;o.textContent='';t.textContent='模型正在响应…';try{const r=await fetch('/v1/chat/completions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({messages:[{role:'user',content:message}],stream:true})});if(r.status===401){loginPrompt();return}if(!r.ok||!r.body)throw Error('暂时无法完成请求。');const reader=r.body.getReader(),d=new TextDecoder();let b='';for(;;){const {done,value}=await reader.read();b+=d.decode(value||new Uint8Array(),{stream:!done});const es=b.split('\\n\\n');b=es.pop()||'';for(const e of es){if(!e.startsWith('data:'))continue;const x=e.slice(5).trim();if(!x||x==='[DONE]')continue;const j=JSON.parse(x),delta=j.choices?.[0]?.delta?.content;if(delta)o.textContent+=delta}if(done)break}t.textContent='完成'}catch(e){t.textContent='请求失败，请稍后重试。'}finally{s.disabled=false}};
p.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')s.click()});
</script></main></body></html>`;
function escapeHtml(value: string): string { return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;"); }
