#!/usr/bin/env bash

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${1:-$PROJECT_ROOT/.env.local}"
COMPOSE_FILE="$PROJECT_ROOT/docker-compose.acceptance.yml"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing acceptance env file: $ENV_FILE" >&2
  exit 2
fi

set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a

: "${ACCEPTANCE_ADMIN_USER:?ACCEPTANCE_ADMIN_USER is required}"
: "${ACCEPTANCE_POSTGRES_DB:?ACCEPTANCE_POSTGRES_DB is required}"
: "${ACCEPTANCE_API_DB_USER:?ACCEPTANCE_API_DB_USER is required}"
: "${ACCEPTANCE_API_DB_PASSWORD:?ACCEPTANCE_API_DB_PASSWORD is required}"
: "${ACCEPTANCE_TRUST_ISSUER_DB_USER:?ACCEPTANCE_TRUST_ISSUER_DB_USER is required}"
: "${ACCEPTANCE_TRUST_ISSUER_DB_PASSWORD:?ACCEPTANCE_TRUST_ISSUER_DB_PASSWORD is required}"
: "${ACCEPTANCE_OUTBOX_DB_USER:?ACCEPTANCE_OUTBOX_DB_USER is required}"
: "${ACCEPTANCE_OUTBOX_DB_PASSWORD:?ACCEPTANCE_OUTBOX_DB_PASSWORD is required}"
: "${ACCEPTANCE_WORKER_A_DB_USER:?ACCEPTANCE_WORKER_A_DB_USER is required}"
: "${ACCEPTANCE_WORKER_A_DB_PASSWORD:?ACCEPTANCE_WORKER_A_DB_PASSWORD is required}"
: "${ACCEPTANCE_WORKER_B_DB_USER:?ACCEPTANCE_WORKER_B_DB_USER is required}"
: "${ACCEPTANCE_WORKER_B_DB_PASSWORD:?ACCEPTANCE_WORKER_B_DB_PASSWORD is required}"
: "${ACCEPTANCE_WORKER_GATEWAY_DB_USER:?ACCEPTANCE_WORKER_GATEWAY_DB_USER is required}"
: "${ACCEPTANCE_WORKER_GATEWAY_DB_PASSWORD:?ACCEPTANCE_WORKER_GATEWAY_DB_PASSWORD is required}"
: "${ACCEPTANCE_REAPER_DB_USER:?ACCEPTANCE_REAPER_DB_USER is required}"
: "${ACCEPTANCE_REAPER_DB_PASSWORD:?ACCEPTANCE_REAPER_DB_PASSWORD is required}"

COMPOSE=(docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE")
"${COMPOSE[@]}" exec -T postgres psql \
  -U "$ACCEPTANCE_ADMIN_USER" -d "$ACCEPTANCE_POSTGRES_DB" \
  -v api_user="$ACCEPTANCE_API_DB_USER" -v api_password="$ACCEPTANCE_API_DB_PASSWORD" \
  -v trust_issuer_user="$ACCEPTANCE_TRUST_ISSUER_DB_USER" -v trust_issuer_password="$ACCEPTANCE_TRUST_ISSUER_DB_PASSWORD" \
  -v outbox_user="$ACCEPTANCE_OUTBOX_DB_USER" -v outbox_password="$ACCEPTANCE_OUTBOX_DB_PASSWORD" \
  -v worker_a_user="$ACCEPTANCE_WORKER_A_DB_USER" -v worker_a_password="$ACCEPTANCE_WORKER_A_DB_PASSWORD" \
  -v worker_b_user="$ACCEPTANCE_WORKER_B_DB_USER" -v worker_b_password="$ACCEPTANCE_WORKER_B_DB_PASSWORD" \
  -v worker_gateway_user="$ACCEPTANCE_WORKER_GATEWAY_DB_USER" -v worker_gateway_password="$ACCEPTANCE_WORKER_GATEWAY_DB_PASSWORD" \
  -v reaper_user="$ACCEPTANCE_REAPER_DB_USER" -v reaper_password="$ACCEPTANCE_REAPER_DB_PASSWORD" \
  -v ON_ERROR_STOP=1 <<'SQL'
SELECT format(
  'CREATE ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD %L',
  :'api_user', :'api_password'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'api_user')\gexec
SELECT format('ALTER ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD %L', :'api_user', :'api_password')\gexec

SELECT format(
  'CREATE ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOBYPASSRLS PASSWORD %L',
  :'trust_issuer_user', :'trust_issuer_password'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'trust_issuer_user')\gexec
SELECT format('ALTER ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOBYPASSRLS PASSWORD %L', :'trust_issuer_user', :'trust_issuer_password')\gexec

SELECT format(
  'CREATE ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD %L',
  :'outbox_user', :'outbox_password'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'outbox_user')\gexec
SELECT format('ALTER ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD %L', :'outbox_user', :'outbox_password')\gexec

SELECT format(
  'CREATE ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD %L',
  :'worker_a_user', :'worker_a_password'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'worker_a_user')\gexec
SELECT format('ALTER ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD %L', :'worker_a_user', :'worker_a_password')\gexec

SELECT format(
  'CREATE ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD %L',
  :'worker_b_user', :'worker_b_password'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'worker_b_user')\gexec
SELECT format('ALTER ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD %L', :'worker_b_user', :'worker_b_password')\gexec

SELECT format(
  'CREATE ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD %L',
  :'worker_gateway_user', :'worker_gateway_password'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'worker_gateway_user')\gexec
SELECT format('ALTER ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD %L', :'worker_gateway_user', :'worker_gateway_password')\gexec

SELECT format(
  'CREATE ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD %L',
  :'reaper_user', :'reaper_password'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'reaper_user')\gexec
SELECT format('ALTER ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD %L', :'reaper_user', :'reaper_password')\gexec
SQL
